aquarius_web_portal_param_names = {
    "temperature": "TEMPERATURA",
    "height": "ALTURA",
    "angle": "ANGULO ELEVACION",
    "atmospheric_pressure": "PRES ATMOS",
    "solar_brightness": "BRILLO SOLAR",
    "relative_solar_brightness": "BRILLO SOLAR RELATIVO",
    "solid_flow": "QS",
    "mean_suspended_sediment": "CM",
    "deuterium": "DEUTERIO",
    "cloud_direction": "DIR NUBOSIDAD",
    "discharge": "CAUDAL",
    "duration": "DURACION",
    "evapotranspiration": "EVAPORACION",
    "atmospheric_anomalies": "FEN ATMOS",
    "gauge": "NIVEL",
    "soil_humidity": "HUM SUELO",
    "cloud": "NUBOSIDAD",
    "oxigen_18": "OXIGENO 18",
    "sample_weight": "PESO MUESTRA",
    "percentage": "PORCENTAJE",
    "rainfall": "PRECIPITACION",
    "UV": "RAD UV",
    "wind_movement": "REC VIENTO",
    "relative_humidity": "HUM RELATIVA",
    "adimensional": "ADIMENSIONAL",
    "soil_temperature": "TEMP SUELO",
    "dew_point": "PUNTO ROCIO",
    "vapor_pressure": "TENSION VAPOR",
    "cloud_type": "TIPO NUBOSIDAD",
    "solar_radiation": "RAD SOLAR",
    "total_suspended_sediment": "CS",
    "mean_suspended_sediment_transport": "TM",
    "tritium": "TRITIO",
    "visibility": "VISIBILIDAD",
    "sample_volume": "VOL MUESTRA",
    "wind_direction": "DIR VIENTO",
    "wind_speed": "VEL VIENTO",
}
