cne_names = {
    "codigo": "id",
    "nombre": "name",
    "categoria": "category",
    "tecnologia": "technology",
    "estado": "status",
    "departamento": "department",
    "municipio": "municipality",
    "altitud": "altitude",
    "longitud": "longitude",
    "latitud": "latitude",
    "fecha_instalacion": "installation_date",
    "fecha_suspension": "suspension_date",
    "area_hidrografica": "hydrographic_area",
    "zona_hidrografica": "hydrographic_zone",
    "subzona_hidrografica": "hydrographic_subzone",
    "entidad": "owner",
}


aquarius_web_portal_param_names = {
    "TEMPERATURA": "temperature",
    "ALTURA": "height",
    "ANGULO ELEVACION": "angle",
    "PRES ATMOS": "atmospheric_pressure",
    "BRILLO SOLAR": "solar_brightness",
    "BRILLO SOLAR RELATIVO": "relative_solar_brightness",
    "QS": "solid_flow",
    "CM": "mean_suspended_sediment",
    "DEUTERIO": "deuterium",
    "DIR NUBOSIDAD": "cloud_direction",
    "CAUDAL": "discharge",
    "DURACION": "duration",
    "EVAPORACION": "evapotranspiration",
    "FEN ATMOS": "atmospheric_anomalies",
    "NIVEL": "gauge",
    "HUM SUELO": "soil_humidity",
    "NUBOSIDAD": "cloud",
    "OXIGENO 18": "oxigen_18",
    "PESO MUESTRA": "sample_weight",
    "PORCENTAJE": "percentage",
    "PRECIPITACION": "rainfall",
    "RAD UV": "UV",
    "REC VIENTO": "wind_movement",
    "HUM RELATIVA": "relative_humidity",
    "ADIMENSIONAL": "adimensional",
    "TEMP SUELO": "soil_temperature",
    "PUNTO ROCIO": "dew_point",
    "TENSION VAPOR": "vapor_pressure",
    "TIPO NUBOSIDAD": "cloud_type",
    "RAD SOLAR": "solar_radiation",
    "CS": "total_suspended_sediment",
    "TM": "mean_suspended_sediment_transport",
    "TRITIO": "tritium",
    "VISIBILIDAD": "visibility",
    "VOL MUESTRA": "sample_volume",
    "DIR VIENTO": "wind_direction",
    "VEL VIENTO": "wind_speed",
}

time_precision_options = {
    "A": "YE",
    "M": "ME",
    "D": "D",
    "H": "H",
}

months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

months_doy_limits = [31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334, 365]
